version: '2'

services:
  ctfd:
    image: ctfd/ctfd
    user: root
    restart: always
    networks:
      default:
      internal:
    ports:
      - "8001:8000"
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - ./CTFd:/opt/CTFd
      - ./solve-webhook-plugin:/opt/CTFd/CTFd/plugins/solve-webhook-plugin
    environment:
      - SECRET_KEY=test_infra_dont_bother
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
      - SOLVE_WEBHOOK_URL=
      - SOLVE_WEBHOOK_LIMIT=3
    depends_on:
      - db
    profiles:
      - ctfd

  db:
    image: mariadb:10.4.12
    restart: always
    networks:
      internal:
    volumes:
      - .data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
      - MYSQL_DATABASE=ctfd
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]
    profiles:
      - ctfd

  cache:
    image: redis:4
    restart: always
    networks:
        internal:
    volumes:
    - .data/redis:/data
    profiles:
      - ctfd
  
  mattermost:
    image: mattermost_webhook
    build: webhooks/mattermost
    environment:
      - MATTERMOST_WEBHOOK_IS_BOT=0
      - MATTERMOST_WEBHOOK_URL=https://mattermost.pwn2own.com/hooks/hook_id
      - MATTERMOST_WEBHOOK_CHANNEL=announcements
      - MATTERMOST_WEBHOOK_USERNAME=the-herald
      - MATTERMOST_WEBHOOK_ICON_EMOJI=trumpet
      - MATTERMOST_WEBHOOK_AUTH_TOKEN=token
    networks:
      default:
      internal:
    ports:
      - "8002:8080"
    profiles:
      - mattermost

networks:
  default:
  internal:
      internal: true
